# Paquetes necesarios

In [1]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
from scipy import stats
%matplotlib inline

def Error_linealizacion(x,y):
    yp = np.mean(y)*np.ones(len(y))
    ei2 = np.sum((y-yp)**2)
    ey = np.sqrt(ei2/(len(y)-2))
    xi2 = np.sum(x**2); Xi2 = np.sum(x)**2
    db = ey*np.sqrt((len(y))/(len(y)*xi2-Xi2)) #pendiente
    da = ey*np.sqrt((xi2)/(len(y)*xi2-Xi2)) #punto de corte
    return np.array([da,db])

# Datos obtenidos en el laboratorio

En primer lugar se debe calibrar cuanto hielo se derrite a temperatura ambiente para poder obtener datos precisos para cada lámina del material, los datos obtenidos fue que se derritió $58.9g$ en $16:40$ minutos, en donde el peso del vaso fue de $49.3g$. El diametro del hielo para esta calibracion es $d = 66.2$ mm

la ecuación a resolver será

$$\frac{\Delta Q}{\Delta t} = \kappa \frac{A}{L}\Delta T$$

Considerando el cambio de energía con el calor latente 

$$\frac{\Delta Q}{\Delta t} = L\frac{\Delta m}{\Delta t}$$

Las tasas de derretiemiendo a temperaturas está dada por 

$$R_{a} = \frac{\Delta m_{amb}}{\Delta t_{amb}} \quad \text{Tasa derretimiento temperatura ambiente}$$
$$R = \frac{\Delta m}{\Delta t} \quad \text{Tasa derretimiento para cada material}$$

Definamos $R_{o} = R-R_{a}$ 

Luego la constante para cada material está dada por 

$$\kappa = \frac{L(R-R_{a})h}{A\Delta T}$$

$$L = 334 \frac{J}{g}$$

In [220]:
ry = 59.2/2 ; rt = 58.7/2; rv = 65.2/2; rb = 59.9/2; rp = 55.9/2 # Radios para cada material en mm 
ty = 384. ; tt = 357.; tv = 155.; tb = 208.; tp = 316. # Tiempo medido en segundos
hy = 8.9; ht = 6.08; hv = 4.7; hb = 6.2; hp = 5.16# mm
my = 91.53; mt = 18.74; mv = 94.75; mb = 20.9; mp = 19.61 # g
L = 334 # Calor latente  kJ/Kg
DT = 369.15 # Kelvin


#mo = np.array([3.1,0.0096,15.9,0,7.8]) #mm. lo que se derrite en temperatura ambiente (Valor que puede variar) 
r = np.array([ry,rt,rv,rb,rp])*1e-3
#mo = 9.6/1000.*np.ones(len(r))
Dt = np.array([ty,tt,tv,tb,tp]) 
h = np.array([hy,ht,hv,hb,hp])*1e-3
Dm = np.array([my,mt,mv,mb,mp])
Ra = 9.6/1000.*np.ones(len(r))

def R(Dm,Dt):
    return Dm/Dt
#Ra= np.array([0.1,0.052,0.1,0,0.059])

def A(r):
    return np.pi*(r**2)

def k(Dt,Dm,h,r):
    
    return h*L*(R(Dm,Dt))/(A(r)*DT)

print "Yeso",k(Dt,Dm,h,r)[0],"LISTO"
print "Triplex",k(Dt,Dm,h,r)[1],"LISTO"
print "Vidrio",k(Dt,Dm,h,r)[2],"LISTO"
print "Baquelita",k(Dt,Dm,h,r)[3]
print "Plexiglass",k(Dt,Dm,h,r)[4],"LISTO"
print ""
print ""
print ""
print ""
print ""



Yeso 0.697320678212654 LISTO
Triplex 0.10670443238223133 LISTO
Vidrio 0.7785811763454905 LISTO
Baquelita 0.20002059210720236
Plexiglass 0.1180511737731459 LISTO







In [221]:
A(r)

array([0.00275254, 0.00270624, 0.00333876, 0.00281802, 0.00245422])

In [211]:
R(Dm,Dt)

array([0.23835938, 0.052493  , 0.61129032, 0.10048077, 0.05978659])

In [212]:
Ra

array([0.096, 0.096, 0.096, 0.096, 0.096])

In [227]:
Dt

array([384., 357., 155., 208., 316.])

In [228]:
Dm

array([91.53, 18.74, 94.75, 20.9 , 19.61])

In [226]:
DM = 0.05
R(Dm,Dt)*np.sqrt((DM/Dm)**2+(Dt**2))

array([91.53, 18.74, 94.75, 20.9 , 19.61])